-- seeders.sql (XACT ERP DEMO v1.2)
-- Generated: 2025-09-16T12:37:07.346589 UTC
-- Includes: roles, full table permissions (CRUD+manage), menu permissions, role-permission mappings, users
BEGIN;

-- Roles
INSERT INTO sy04_role (role_name, status) VALUES
('Admin', 1),
('Manager', 1),
('Clerk', 1)
ON CONFLICT (role_name) DO NOTHING;

-- Permissions (table + menu)
INSERT INTO sy05_perm (perm_name, description, status)
VALUES
('sy.user.view', 'VIEW permission for sy00_user (sy.user)', 1),
('sy.user.create', 'CREATE permission for sy00_user (sy.user)', 1),
('sy.user.update', 'UPDATE permission for sy00_user (sy.user)', 1),
('sy.user.delete', 'DELETE permission for sy00_user (sy.user)', 1),
('sy.user.manage', 'MANAGE permission for sy00_user (sy.user)', 1),
('sy.role.view', 'VIEW permission for sy04_role (sy.role)', 1),
('sy.role.create', 'CREATE permission for sy04_role (sy.role)', 1),
('sy.role.update', 'UPDATE permission for sy04_role (sy.role)', 1),
('sy.role.delete', 'DELETE permission for sy04_role (sy.role)', 1),
('sy.role.manage', 'MANAGE permission for sy04_role (sy.role)', 1),
('sy.permission.view', 'VIEW permission for sy05_perm (sy.permission)', 1),
('sy.permission.create', 'CREATE permission for sy05_perm (sy.permission)', 1),
('sy.permission.update', 'UPDATE permission for sy05_perm (sy.permission)', 1),
('sy.permission.delete', 'DELETE permission for sy05_perm (sy.permission)', 1),
('sy.permission.manage', 'MANAGE permission for sy05_perm (sy.permission)', 1),
('sy.role_permission.view', 'VIEW permission for sy06_role_perm (sy.role_permission)', 1),
('sy.role_permission.create', 'CREATE permission for sy06_role_perm (sy.role_permission)', 1),
('sy.role_permission.update', 'UPDATE permission for sy06_role_perm (sy.role_permission)', 1),
('sy.role_permission.delete', 'DELETE permission for sy06_role_perm (sy.role_permission)', 1),
('sy.role_permission.manage', 'MANAGE permission for sy06_role_perm (sy.role_permission)', 1),
('sy.session.view', 'VIEW permission for sy01_sess (sy.session)', 1),
('sy.session.create', 'CREATE permission for sy01_sess (sy.session)', 1),
('sy.session.update', 'UPDATE permission for sy01_sess (sy.session)', 1),
('sy.session.delete', 'DELETE permission for sy01_sess (sy.session)', 1),
('sy.session.manage', 'MANAGE permission for sy01_sess (sy.session)', 1),
('sy.log.view', 'VIEW permission for sy02_logs (sy.log)', 1),
('sy.log.create', 'CREATE permission for sy02_logs (sy.log)', 1),
('sy.log.update', 'UPDATE permission for sy02_logs (sy.log)', 1),
('sy.log.delete', 'DELETE permission for sy02_logs (sy.log)', 1),
('sy.log.manage', 'MANAGE permission for sy02_logs (sy.log)', 1),
('sy.setting.view', 'VIEW permission for sy03_sett (sy.setting)', 1),
('sy.setting.create', 'CREATE permission for sy03_sett (sy.setting)', 1),
('sy.setting.update', 'UPDATE permission for sy03_sett (sy.setting)', 1),
('sy.setting.delete', 'DELETE permission for sy03_sett (sy.setting)', 1),
('sy.setting.manage', 'MANAGE permission for sy03_sett (sy.setting)', 1),
('sy.history.view', 'VIEW permission for sy40_hist (sy.history)', 1),
('sy.history.create', 'CREATE permission for sy40_hist (sy.history)', 1),
('sy.history.update', 'UPDATE permission for sy40_hist (sy.history)', 1),
('sy.history.delete', 'DELETE permission for sy40_hist (sy.history)', 1),
('sy.history.manage', 'MANAGE permission for sy40_hist (sy.history)', 1),
('dl.customer.view', 'VIEW permission for dl01_mast (dl.customer)', 1),
('dl.customer.create', 'CREATE permission for dl01_mast (dl.customer)', 1),
('dl.customer.update', 'UPDATE permission for dl01_mast (dl.customer)', 1),
('dl.customer.delete', 'DELETE permission for dl01_mast (dl.customer)', 1),
('dl.customer.manage', 'MANAGE permission for dl01_mast (dl.customer)', 1),
('dl.transaction.view', 'VIEW permission for dl30_trans (dl.transaction)', 1),
('dl.transaction.create', 'CREATE permission for dl30_trans (dl.transaction)', 1),
('dl.transaction.update', 'UPDATE permission for dl30_trans (dl.transaction)', 1),
('dl.transaction.delete', 'DELETE permission for dl30_trans (dl.transaction)', 1),
('dl.transaction.manage', 'MANAGE permission for dl30_trans (dl.transaction)', 1),
('dl.history.view', 'VIEW permission for dl40_hist (dl.history)', 1),
('dl.history.create', 'CREATE permission for dl40_hist (dl.history)', 1),
('dl.history.update', 'UPDATE permission for dl40_hist (dl.history)', 1),
('dl.history.delete', 'DELETE permission for dl40_hist (dl.history)', 1),
('dl.history.manage', 'MANAGE permission for dl40_hist (dl.history)', 1),
('cl.supplier.view', 'VIEW permission for cl01_mast (cl.supplier)', 1),
('cl.supplier.create', 'CREATE permission for cl01_mast (cl.supplier)', 1),
('cl.supplier.update', 'UPDATE permission for cl01_mast (cl.supplier)', 1),
('cl.supplier.delete', 'DELETE permission for cl01_mast (cl.supplier)', 1),
('cl.supplier.manage', 'MANAGE permission for cl01_mast (cl.supplier)', 1),
('cl.transaction.view', 'VIEW permission for cl30_trans (cl.transaction)', 1),
('cl.transaction.create', 'CREATE permission for cl30_trans (cl.transaction)', 1),
('cl.transaction.update', 'UPDATE permission for cl30_trans (cl.transaction)', 1),
('cl.transaction.delete', 'DELETE permission for cl30_trans (cl.transaction)', 1),
('cl.transaction.manage', 'MANAGE permission for cl30_trans (cl.transaction)', 1),
('cl.history.view', 'VIEW permission for cl40_hist (cl.history)', 1),
('cl.history.create', 'CREATE permission for cl40_hist (cl.history)', 1),
('cl.history.update', 'UPDATE permission for cl40_hist (cl.history)', 1),
('cl.history.delete', 'DELETE permission for cl40_hist (cl.history)', 1),
('cl.history.manage', 'MANAGE permission for cl40_hist (cl.history)', 1),
('st.category.view', 'VIEW permission for st02_mast (st.category)', 1),
('st.category.create', 'CREATE permission for st02_mast (st.category)', 1),
('st.category.update', 'UPDATE permission for st02_mast (st.category)', 1),
('st.category.delete', 'DELETE permission for st02_mast (st.category)', 1),
('st.category.manage', 'MANAGE permission for st02_mast (st.category)', 1),
('st.item.view', 'VIEW permission for st01_mast (st.item)', 1),
('st.item.create', 'CREATE permission for st01_mast (st.item)', 1),
('st.item.update', 'UPDATE permission for st01_mast (st.item)', 1),
('st.item.delete', 'DELETE permission for st01_mast (st.item)', 1),
('st.item.manage', 'MANAGE permission for st01_mast (st.item)', 1),
('st.transaction.view', 'VIEW permission for st30_trans (st.transaction)', 1),
('st.transaction.create', 'CREATE permission for st30_trans (st.transaction)', 1),
('st.transaction.update', 'UPDATE permission for st30_trans (st.transaction)', 1),
('st.transaction.delete', 'DELETE permission for st30_trans (st.transaction)', 1),
('st.transaction.manage', 'MANAGE permission for st30_trans (st.transaction)', 1),
('st.history.view', 'VIEW permission for st40_hist (st.history)', 1),
('st.history.create', 'CREATE permission for st40_hist (st.history)', 1),
('st.history.update', 'UPDATE permission for st40_hist (st.history)', 1),
('st.history.delete', 'DELETE permission for st40_hist (st.history)', 1),
('st.history.manage', 'MANAGE permission for st40_hist (st.history)', 1),
('wh.warehouse.view', 'VIEW permission for wh01_mast (wh.warehouse)', 1),
('wh.warehouse.create', 'CREATE permission for wh01_mast (wh.warehouse)', 1),
('wh.warehouse.update', 'UPDATE permission for wh01_mast (wh.warehouse)', 1),
('wh.warehouse.delete', 'DELETE permission for wh01_mast (wh.warehouse)', 1),
('wh.warehouse.manage', 'MANAGE permission for wh01_mast (wh.warehouse)', 1),
('wh.allowed_category.view', 'VIEW permission for wh02_mast (wh.allowed_category)', 1),
('wh.allowed_category.create', 'CREATE permission for wh02_mast (wh.allowed_category)', 1),
('wh.allowed_category.update', 'UPDATE permission for wh02_mast (wh.allowed_category)', 1),
('wh.allowed_category.delete', 'DELETE permission for wh02_mast (wh.allowed_category)', 1),
('wh.allowed_category.manage', 'MANAGE permission for wh02_mast (wh.allowed_category)', 1),
('wh.transaction.view', 'VIEW permission for wh30_trans (wh.transaction)', 1),
('wh.transaction.create', 'CREATE permission for wh30_trans (wh.transaction)', 1),
('wh.transaction.update', 'UPDATE permission for wh30_trans (wh.transaction)', 1),
('wh.transaction.delete', 'DELETE permission for wh30_trans (wh.transaction)', 1),
('wh.transaction.manage', 'MANAGE permission for wh30_trans (wh.transaction)', 1),
('wh.history.view', 'VIEW permission for wh40_hist (wh.history)', 1),
('wh.history.create', 'CREATE permission for wh40_hist (wh.history)', 1),
('wh.history.update', 'UPDATE permission for wh40_hist (wh.history)', 1),
('wh.history.delete', 'DELETE permission for wh40_hist (wh.history)', 1),
('wh.history.manage', 'MANAGE permission for wh40_hist (wh.history)', 1),
('wb.bin.view', 'VIEW permission for wb01_mast (wb.bin)', 1),
('wb.bin.create', 'CREATE permission for wb01_mast (wb.bin)', 1),
('wb.bin.update', 'UPDATE permission for wb01_mast (wb.bin)', 1),
('wb.bin.delete', 'DELETE permission for wb01_mast (wb.bin)', 1),
('wb.bin.manage', 'MANAGE permission for wb01_mast (wb.bin)', 1),
('wb.transaction.view', 'VIEW permission for wb30_trans (wb.transaction)', 1),
('wb.transaction.create', 'CREATE permission for wb30_trans (wb.transaction)', 1),
('wb.transaction.update', 'UPDATE permission for wb30_trans (wb.transaction)', 1),
('wb.transaction.delete', 'DELETE permission for wb30_trans (wb.transaction)', 1),
('wb.transaction.manage', 'MANAGE permission for wb30_trans (wb.transaction)', 1),
('wb.history.view', 'VIEW permission for wb40_hist (wb.history)', 1),
('wb.history.create', 'CREATE permission for wb40_hist (wb.history)', 1),
('wb.history.update', 'UPDATE permission for wb40_hist (wb.history)', 1),
('wb.history.delete', 'DELETE permission for wb40_hist (wb.history)', 1),
('wb.history.manage', 'MANAGE permission for wb40_hist (wb.history)', 1),
('sa.base_hdr.view', 'VIEW permission for sa30_hdr (sa.base_hdr)', 1),
('sa.base_hdr.create', 'CREATE permission for sa30_hdr (sa.base_hdr)', 1),
('sa.base_hdr.update', 'UPDATE permission for sa30_hdr (sa.base_hdr)', 1),
('sa.base_hdr.delete', 'DELETE permission for sa30_hdr (sa.base_hdr)', 1),
('sa.base_hdr.manage', 'MANAGE permission for sa30_hdr (sa.base_hdr)', 1),
('sa.base_det.view', 'VIEW permission for sa30_det (sa.base_det)', 1),
('sa.base_det.create', 'CREATE permission for sa30_det (sa.base_det)', 1),
('sa.base_det.update', 'UPDATE permission for sa30_det (sa.base_det)', 1),
('sa.base_det.delete', 'DELETE permission for sa30_det (sa.base_det)', 1),
('sa.base_det.manage', 'MANAGE permission for sa30_det (sa.base_det)', 1),
('sa.base_hist.view', 'VIEW permission for sa40_hist (sa.base_hist)', 1),
('sa.base_hist.create', 'CREATE permission for sa40_hist (sa.base_hist)', 1),
('sa.base_hist.update', 'UPDATE permission for sa40_hist (sa.base_hist)', 1),
('sa.base_hist.delete', 'DELETE permission for sa40_hist (sa.base_hist)', 1),
('sa.base_hist.manage', 'MANAGE permission for sa40_hist (sa.base_hist)', 1),
('sa.quote_hdr.view', 'VIEW permission for sa31_hdr (sa.quote_hdr)', 1),
('sa.quote_hdr.create', 'CREATE permission for sa31_hdr (sa.quote_hdr)', 1),
('sa.quote_hdr.update', 'UPDATE permission for sa31_hdr (sa.quote_hdr)', 1),
('sa.quote_hdr.delete', 'DELETE permission for sa31_hdr (sa.quote_hdr)', 1),
('sa.quote_hdr.manage', 'MANAGE permission for sa31_hdr (sa.quote_hdr)', 1),
('sa.quote_det.view', 'VIEW permission for sa31_det (sa.quote_det)', 1),
('sa.quote_det.create', 'CREATE permission for sa31_det (sa.quote_det)', 1),
('sa.quote_det.update', 'UPDATE permission for sa31_det (sa.quote_det)', 1),
('sa.quote_det.delete', 'DELETE permission for sa31_det (sa.quote_det)', 1),
('sa.quote_det.manage', 'MANAGE permission for sa31_det (sa.quote_det)', 1),
('sa.quote_hist.view', 'VIEW permission for sa41_hist (sa.quote_hist)', 1),
('sa.quote_hist.create', 'CREATE permission for sa41_hist (sa.quote_hist)', 1),
('sa.quote_hist.update', 'UPDATE permission for sa41_hist (sa.quote_hist)', 1),
('sa.quote_hist.delete', 'DELETE permission for sa41_hist (sa.quote_hist)', 1),
('sa.quote_hist.manage', 'MANAGE permission for sa41_hist (sa.quote_hist)', 1),
('sa.invoice_hdr.view', 'VIEW permission for sa32_hdr (sa.invoice_hdr)', 1),
('sa.invoice_hdr.create', 'CREATE permission for sa32_hdr (sa.invoice_hdr)', 1),
('sa.invoice_hdr.update', 'UPDATE permission for sa32_hdr (sa.invoice_hdr)', 1),
('sa.invoice_hdr.delete', 'DELETE permission for sa32_hdr (sa.invoice_hdr)', 1),
('sa.invoice_hdr.manage', 'MANAGE permission for sa32_hdr (sa.invoice_hdr)', 1),
('sa.invoice_det.view', 'VIEW permission for sa32_det (sa.invoice_det)', 1),
('sa.invoice_det.create', 'CREATE permission for sa32_det (sa.invoice_det)', 1),
('sa.invoice_det.update', 'UPDATE permission for sa32_det (sa.invoice_det)', 1),
('sa.invoice_det.delete', 'DELETE permission for sa32_det (sa.invoice_det)', 1),
('sa.invoice_det.manage', 'MANAGE permission for sa32_det (sa.invoice_det)', 1),
('sa.invoice_hist.view', 'VIEW permission for sa42_hist (sa.invoice_hist)', 1),
('sa.invoice_hist.create', 'CREATE permission for sa42_hist (sa.invoice_hist)', 1),
('sa.invoice_hist.update', 'UPDATE permission for sa42_hist (sa.invoice_hist)', 1),
('sa.invoice_hist.delete', 'DELETE permission for sa42_hist (sa.invoice_hist)', 1),
('sa.invoice_hist.manage', 'MANAGE permission for sa42_hist (sa.invoice_hist)', 1),
('sa.credit_hdr.view', 'VIEW permission for sa33_hdr (sa.credit_hdr)', 1),
('sa.credit_hdr.create', 'CREATE permission for sa33_hdr (sa.credit_hdr)', 1),
('sa.credit_hdr.update', 'UPDATE permission for sa33_hdr (sa.credit_hdr)', 1),
('sa.credit_hdr.delete', 'DELETE permission for sa33_hdr (sa.credit_hdr)', 1),
('sa.credit_hdr.manage', 'MANAGE permission for sa33_hdr (sa.credit_hdr)', 1),
('sa.credit_det.view', 'VIEW permission for sa33_det (sa.credit_det)', 1),
('sa.credit_det.create', 'CREATE permission for sa33_det (sa.credit_det)', 1),
('sa.credit_det.update', 'UPDATE permission for sa33_det (sa.credit_det)', 1),
('sa.credit_det.delete', 'DELETE permission for sa33_det (sa.credit_det)', 1),
('sa.credit_det.manage', 'MANAGE permission for sa33_det (sa.credit_det)', 1),
('sa.credit_hist.view', 'VIEW permission for sa43_hist (sa.credit_hist)', 1),
('sa.credit_hist.create', 'CREATE permission for sa43_hist (sa.credit_hist)', 1),
('sa.credit_hist.update', 'UPDATE permission for sa43_hist (sa.credit_hist)', 1),
('sa.credit_hist.delete', 'DELETE permission for sa43_hist (sa.credit_hist)', 1),
('sa.credit_hist.manage', 'MANAGE permission for sa43_hist (sa.credit_hist)', 1),
('pu.invoice_hdr.view', 'VIEW permission for pu30_hdr (pu.invoice_hdr)', 1),
('pu.invoice_hdr.create', 'CREATE permission for pu30_hdr (pu.invoice_hdr)', 1),
('pu.invoice_hdr.update', 'UPDATE permission for pu30_hdr (pu.invoice_hdr)', 1),
('pu.invoice_hdr.delete', 'DELETE permission for pu30_hdr (pu.invoice_hdr)', 1),
('pu.invoice_hdr.manage', 'MANAGE permission for pu30_hdr (pu.invoice_hdr)', 1),
('pu.invoice_det.view', 'VIEW permission for pu30_det (pu.invoice_det)', 1),
('pu.invoice_det.create', 'CREATE permission for pu30_det (pu.invoice_det)', 1),
('pu.invoice_det.update', 'UPDATE permission for pu30_det (pu.invoice_det)', 1),
('pu.invoice_det.delete', 'DELETE permission for pu30_det (pu.invoice_det)', 1),
('pu.invoice_det.manage', 'MANAGE permission for pu30_det (pu.invoice_det)', 1),
('pu.invoice_hist.view', 'VIEW permission for pu40_hist (pu.invoice_hist)', 1),
('pu.invoice_hist.create', 'CREATE permission for pu40_hist (pu.invoice_hist)', 1),
('pu.invoice_hist.update', 'UPDATE permission for pu40_hist (pu.invoice_hist)', 1),
('pu.invoice_hist.delete', 'DELETE permission for pu40_hist (pu.invoice_hist)', 1),
('pu.invoice_hist.manage', 'MANAGE permission for pu40_hist (pu.invoice_hist)', 1),
('pu.order_hdr.view', 'VIEW permission for pu31_hdr (pu.order_hdr)', 1),
('pu.order_hdr.create', 'CREATE permission for pu31_hdr (pu.order_hdr)', 1),
('pu.order_hdr.update', 'UPDATE permission for pu31_hdr (pu.order_hdr)', 1),
('pu.order_hdr.delete', 'DELETE permission for pu31_hdr (pu.order_hdr)', 1),
('pu.order_hdr.manage', 'MANAGE permission for pu31_hdr (pu.order_hdr)', 1),
('pu.order_det.view', 'VIEW permission for pu31_det (pu.order_det)', 1),
('pu.order_det.create', 'CREATE permission for pu31_det (pu.order_det)', 1),
('pu.order_det.update', 'UPDATE permission for pu31_det (pu.order_det)', 1),
('pu.order_det.delete', 'DELETE permission for pu31_det (pu.order_det)', 1),
('pu.order_det.manage', 'MANAGE permission for pu31_det (pu.order_det)', 1),
('pu.order_hist.view', 'VIEW permission for pu41_hist (pu.order_hist)', 1),
('pu.order_hist.create', 'CREATE permission for pu41_hist (pu.order_hist)', 1),
('pu.order_hist.update', 'UPDATE permission for pu41_hist (pu.order_hist)', 1),
('pu.order_hist.delete', 'DELETE permission for pu41_hist (pu.order_hist)', 1),
('pu.order_hist.manage', 'MANAGE permission for pu41_hist (pu.order_hist)', 1),
('gl.account.view', 'VIEW permission for gl01_acc (gl.account)', 1),
('gl.account.create', 'CREATE permission for gl01_acc (gl.account)', 1),
('gl.account.update', 'UPDATE permission for gl01_acc (gl.account)', 1),
('gl.account.delete', 'DELETE permission for gl01_acc (gl.account)', 1),
('gl.account.manage', 'MANAGE permission for gl01_acc (gl.account)', 1),
('gl.journal.view', 'VIEW permission for gl30_jnl (gl.journal)', 1),
('gl.journal.create', 'CREATE permission for gl30_jnl (gl.journal)', 1),
('gl.journal.update', 'UPDATE permission for gl30_jnl (gl.journal)', 1),
('gl.journal.delete', 'DELETE permission for gl30_jnl (gl.journal)', 1),
('gl.journal.manage', 'MANAGE permission for gl30_jnl (gl.journal)', 1),
('gl.journal_line.view', 'VIEW permission for gl31_det (gl.journal_line)', 1),
('gl.journal_line.create', 'CREATE permission for gl31_det (gl.journal_line)', 1),
('gl.journal_line.update', 'UPDATE permission for gl31_det (gl.journal_line)', 1),
('gl.journal_line.delete', 'DELETE permission for gl31_det (gl.journal_line)', 1),
('gl.journal_line.manage', 'MANAGE permission for gl31_det (gl.journal_line)', 1),
('gl.history.view', 'VIEW permission for gl40_hist (gl.history)', 1),
('gl.history.create', 'CREATE permission for gl40_hist (gl.history)', 1),
('gl.history.update', 'UPDATE permission for gl40_hist (gl.history)', 1),
('gl.history.delete', 'DELETE permission for gl40_hist (gl.history)', 1),
('gl.history.manage', 'MANAGE permission for gl40_hist (gl.history)', 1),
('payt.payment.view', 'VIEW permission for payt30_hdr (payt.payment)', 1),
('payt.payment.create', 'CREATE permission for payt30_hdr (payt.payment)', 1),
('payt.payment.update', 'UPDATE permission for payt30_hdr (payt.payment)', 1),
('payt.payment.delete', 'DELETE permission for payt30_hdr (payt.payment)', 1),
('payt.payment.manage', 'MANAGE permission for payt30_hdr (payt.payment)', 1),
('payt.history.view', 'VIEW permission for payt40_hist (payt.history)', 1),
('payt.history.create', 'CREATE permission for payt40_hist (payt.history)', 1),
('payt.history.update', 'UPDATE permission for payt40_hist (payt.history)', 1),
('payt.history.delete', 'DELETE permission for payt40_hist (payt.history)', 1),
('payt.history.manage', 'MANAGE permission for payt40_hist (payt.history)', 1),
('sy.menu.access', 'Access SY module menu', 1),
('sy.menu.users.access', 'Access SY Users Access menu', 1),
('sy.menu.roles.access', 'Access SY Roles Access menu', 1),
('sy.menu.permissions.access', 'Access SY Permissions Access menu', 1),
('sy.menu.settings.access', 'Access SY Settings Access menu', 1),
('sy.menu.logs.access', 'Access SY Logs Access menu', 1),
('dl.menu.access', 'Access DL module menu', 1),
('dl.menu.customers.access', 'Access DL Customers Access menu', 1),
('dl.menu.transactions.access', 'Access DL Transactions Access menu', 1),
('cl.menu.access', 'Access CL module menu', 1),
('cl.menu.suppliers.access', 'Access CL Suppliers Access menu', 1),
('cl.menu.transactions.access', 'Access CL Transactions Access menu', 1),
('st.menu.access', 'Access ST module menu', 1),
('st.menu.items.access', 'Access ST Items Access menu', 1),
('st.menu.categories.access', 'Access ST Categories Access menu', 1),
('st.menu.transactions.access', 'Access ST Transactions Access menu', 1),
('wh.menu.access', 'Access WH module menu', 1),
('wh.menu.warehouses.access', 'Access WH Warehouses Access menu', 1),
('wb.menu.access', 'Access WB module menu', 1),
('wb.menu.bins.access', 'Access WB Bins Access menu', 1),
('wb.menu.transactions.access', 'Access WB Transactions Access menu', 1),
('sa.menu.access', 'Access SA module menu', 1),
('sa.menu.quotes.access', 'Access SA Quotes Access menu', 1),
('sa.menu.invoices.access', 'Access SA Invoices Access menu', 1),
('sa.menu.credits.access', 'Access SA Credits Access menu', 1),
('pu.menu.access', 'Access PU module menu', 1),
('pu.menu.orders.access', 'Access PU Orders Access menu', 1),
('pu.menu.invoices.access', 'Access PU Invoices Access menu', 1),
('gl.menu.access', 'Access GL module menu', 1),
('gl.menu.accounts.access', 'Access GL Accounts Access menu', 1),
('gl.menu.journals.access', 'Access GL Journals Access menu', 1),
('gl.menu.reports.access', 'Access GL Reports Access menu', 1),
('payt.menu.access', 'Access PAYT module menu', 1),
('app.menu.main.access', 'Access main application menu', 1)
ON CONFLICT (perm_name) DO NOTHING;

-- Role-Permission mapping
-- Admin gets ALL permissions
INSERT INTO sy06_role_perm (role_id, perm_id)
SELECT r.id, p.id
FROM sy04_role r CROSS JOIN sy05_perm p
WHERE r.role_name='Admin'
ON CONFLICT DO NOTHING;

INSERT INTO sy06_role_perm (role_id, perm_id)
SELECT r.id, p.id
FROM sy04_role r
JOIN sy05_perm p ON p.perm_name IN ('app.menu.main.access', 'dl.menu.access', 'dl.menu.customers.access', 'dl.menu.transactions.access', 'cl.menu.access', 'cl.menu.suppliers.access', 'cl.menu.transactions.access', 'st.menu.access', 'st.menu.items.access', 'st.menu.categories.access', 'st.menu.transactions.access', 'wh.menu.access', 'wb.menu.access', 'wb.menu.bins.access', 'wb.menu.transactions.access', 'sa.menu.access', 'sa.menu.quotes.access', 'sa.menu.invoices.access', 'sa.menu.credits.access', 'pu.menu.access', 'pu.menu.orders.access', 'pu.menu.invoices.access', 'gl.menu.access', 'gl.menu.accounts.access', 'gl.menu.journals.access', 'gl.menu.reports.access', 'payt.menu.access', 'dl.customer.view', 'dl.customer.create', 'dl.customer.update', 'dl.transaction.view', 'cl.supplier.view', 'cl.supplier.create', 'cl.supplier.update', 'cl.transaction.view', 'st.item.view', 'st.item.create', 'st.item.update', 'st.category.view', 'st.transaction.view', 'wh.warehouse.view', 'wb.bin.view', 'sa.quote_hdr.view', 'sa.quote_hdr.create', 'sa.quote_hdr.update', 'sa.quote_det.view', 'sa.quote_det.create', 'sa.quote_det.update', 'sa.invoice_hdr.view', 'sa.invoice_hdr.create', 'sa.invoice_hdr.update', 'sa.invoice_det.view', 'sa.invoice_det.create', 'sa.invoice_det.update', 'sa.credit_hdr.view', 'sa.credit_hdr.create', 'sa.credit_hdr.update', 'sa.credit_det.view', 'sa.credit_det.create', 'sa.credit_det.update', 'pu.order_hdr.view', 'pu.order_hdr.create', 'pu.order_hdr.update', 'pu.order_det.view', 'pu.order_det.create', 'pu.order_det.update', 'pu.invoice_hdr.view', 'pu.invoice_hdr.create', 'pu.invoice_hdr.update', 'pu.invoice_det.view', 'pu.invoice_det.create', 'pu.invoice_det.update', 'payt.payment.view', 'payt.payment.create', 'gl.account.view', 'gl.journal.view', 'gl.journal.create', 'gl.journal.update', 'dl.history.view', 'cl.history.view', 'st.history.view', 'wh.history.view', 'wb.history.view', 'sa.base_hist.view', 'sa.quote_hist.view', 'sa.invoice_hist.view', 'sa.credit_hist.view', 'pu.invoice_hist.view', 'pu.order_hist.view', 'gl.history.view', 'payt.history.view')
WHERE r.role_name='Manager'
ON CONFLICT DO NOTHING;

INSERT INTO sy06_role_perm (role_id, perm_id)
SELECT r.id, p.id
FROM sy04_role r
JOIN sy05_perm p ON p.perm_name IN ('app.menu.main.access', 'dl.menu.access', 'dl.menu.customers.access', 'st.menu.access', 'st.menu.items.access', 'sa.menu.access', 'sa.menu.invoices.access', 'payt.menu.access', 'dl.customer.view', 'st.item.view', 'sa.invoice_hdr.view', 'sa.invoice_hdr.create', 'sa.invoice_hdr.update', 'sa.invoice_det.view', 'sa.invoice_det.create', 'sa.invoice_det.update', 'payt.payment.view', 'payt.payment.create', 'sa.invoice_hist.view')
WHERE r.role_name='Clerk'
ON CONFLICT DO NOTHING;

-- Users (replace password hashes with real bcrypt)

INSERT INTO sy00_user (username, full_name, email, password, role_id, status, created_at)
VALUES
('admin','Administrator','admin@example.com','$2y$bcrypt_hash_placeholder',(SELECT id FROM sy04_role WHERE role_name='Admin'),1,now()),
('manager1','Manager One','manager1@example.com','$2y$bcrypt_hash_placeholder',(SELECT id FROM sy04_role WHERE role_name='Manager'),1,now()),
('manager2','Manager Two','manager2@example.com','$2y$bcrypt_hash_placeholder',(SELECT id FROM sy04_role WHERE role_name='Manager'),1,now()),
('manager3','Manager Three','manager3@example.com','$2y$bcrypt_hash_placeholder',(SELECT id FROM sy04_role WHERE role_name='Manager'),1,now()),
('clerk1','Clerk One','clerk1@example.com','$2y$bcrypt_hash_placeholder',(SELECT id FROM sy04_role WHERE role_name='Clerk'),1,now()),
('clerk2','Clerk Two','clerk2@example.com','$2y$bcrypt_hash_placeholder',(SELECT id FROM sy04_role WHERE role_name='Clerk'),1,now()),
('clerk3','Clerk Three','clerk3@example.com','$2y$bcrypt_hash_placeholder',(SELECT id FROM sy04_role WHERE role_name='Clerk'),1,now()),
('clerk4','Clerk Four','clerk4@example.com','$2y$bcrypt_hash_placeholder',(SELECT id FROM sy04_role WHERE role_name='Clerk'),1,now()),
('clerk5','Clerk Five','clerk5@example.com','$2y$bcrypt_hash_placeholder',(SELECT id FROM sy04_role WHERE role_name='Clerk'),1,now()),
('clerk6','Clerk Six','clerk6@example.com','$2y$bcrypt_hash_placeholder',(SELECT id FROM sy04_role WHERE role_name='Clerk'),1,now())
ON CONFLICT (username) DO NOTHING;


-- Starter settings
INSERT INTO sy03_sett (sett_key, sett_value, description) VALUES
('company.name','XACT Demo Company','Company legal/trading name'),
('company.vat_no','ZA-123456789','VAT number'),
('ui.theme','dark','Default UI theme')
ON CONFLICT (sett_key) DO UPDATE SET sett_value=EXCLUDED.sett_value, description=EXCLUDED.description, updated_at=now();

COMMIT;